name: thesis
channels:
 - defaults
 - conda-forge
 - fastai
 - pytorch
dependencies:
 - python>=3.9.0
 - numpy>=1.21.2
 - matplotlib>=3.2.2
 - pillow>=7.1.2
 - pytorch::torchvision>=0.12.0
 - pandas>=1.1.4
 - seaborn>=0.11.2
 - pytorch::pytorch>=1.10.0
 # above dependencies are for yolov5
 # other ai libraries
 - tensorflow-gpu
 - fastai::fastai
 # utilities
 - ffmpeg
 - jupyterlab
 # Yolov5
 - pyyaml>=5.3.1
 - requests>=2.23.0
 - scipy>=1.4.1
 - tqdm>=4.61.2
 - tensorboard>=2.4.1
 # HybridNets
 - fastai::albumentations>=1.1.0
 - efficientnet-pytorch>=0.7.1
 - pretrainedmodels>=0.7.4
 - fastai::timm>=0.5.4
 - webcolors>=1.11.1
 - pip
 - pip:
   - prefetch_generator>=1.0.1
   - opencv-python>=4.5.1
