name: thesis
channels:
 - defaults
 - conda-forge
 - fastai
 - pytorch
dependencies:
 - python>=3.9.0
 - numpy>=1.21.2
 - matplotlib>=3.2.2
 - opencv>=4.5.1
 - pillow>=7.1.2
 - pytorch::torchvision>=0.12.0
 - pandas>=1.1.4
 - seaborn>=0.11.2
 - pytorch>=1.10.0
 # above dependencies are for yolov5
 # other ai libraries
 - tensorflow-gpu
 - fastai
 # utilities
 - ffmpeg
 - jupyterlab
 # yolov5
 - pyyaml>=5.3.1
 - requests>=2.23.0
 - scipy>=1.4.1
 - tqdm>=4.61.2
 - tensorboard>=2.4.1
